# Homebrew formula for `coord`. Auto-generated by scripts/release-formula.sh
# from each tagged release. Do not hand-edit.
#
# Install via the tap:
#   brew tap dmarshaltu/coord
#   brew install coord
class Coord < Formula
  desc "Local coordinator for parallel AI coding agents (MCP + A2A, atomic claims)"
  homepage "https://github.com/DmarshalTU/coord"
  license "MIT"
  version "0.4.1"

  # Pre-built binaries: Apple Silicon macOS and x86_64 Linux. On other
  # architectures, install from source:
  #   cargo install --git https://github.com/DmarshalTU/coord
  on_macos do
    on_arm do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-aarch64-apple-darwin"
      sha256 "37b5ed87b15b11efe21401706684d703327d35c34f08767b69d2b613acff6599"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-x86_64-unknown-linux-gnu"
      sha256 "89c9540bc30c3db4d0f8d76e938f26b48c57e1a718dab32cb94d13fbf2382d45"
    end
  end

  def install
    bin.install Dir["coord-*"].first => "coord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coord version")
  end
end
