# Homebrew formula for `coord`. Auto-generated by scripts/release-formula.sh
# from each tagged release. Do not hand-edit.
#
# Install via the tap:
#   brew tap dmarshaltu/coord
#   brew install coord
class Coord < Formula
  desc "Local coordinator for parallel AI coding agents (MCP + A2A, atomic claims)"
  homepage "https://github.com/DmarshalTU/coord"
  license "MIT"
  version "0.3.1"

  # Pre-built binaries: Apple Silicon macOS and x86_64 Linux. On other
  # architectures, install from source:
  #   cargo install --git https://github.com/DmarshalTU/coord
  on_macos do
    on_arm do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-aarch64-apple-darwin"
      sha256 "102bc0b0498fd86203982c2186fd30749b507ff9ed6ff6d0307291d081badce2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-x86_64-unknown-linux-gnu"
      sha256 "f9281cc0601488abd96e134f6fe8d0f39c46c2a7794860813a057f00c3c406a6"
    end
  end

  def install
    bin.install Dir["coord-*"].first => "coord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coord version")
  end
end
