# Homebrew formula for `coord`. Auto-generated by scripts/release-formula.sh
# from each tagged release. Do not hand-edit.
#
# Install via the tap:
#   brew tap dmarshaltu/coord
#   brew install coord
class Coord < Formula
  desc "Local coordinator for parallel AI coding agents (MCP + A2A, atomic claims)"
  homepage "https://github.com/DmarshalTU/coord"
  license "MIT"
  version "0.4.0"

  # Pre-built binaries: Apple Silicon macOS and x86_64 Linux. On other
  # architectures, install from source:
  #   cargo install --git https://github.com/DmarshalTU/coord
  on_macos do
    on_arm do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-aarch64-apple-darwin"
      sha256 "73fb4bb08f39ca6886a6eaf6d7abb3aeb166513109e4308adca700d7131069fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DmarshalTU/coord/releases/download/v#{version}/coord-x86_64-unknown-linux-gnu"
      sha256 "5a9d957883368bb695edbb0013d42c2633c08c46d498b79578f306a9fcca6f82"
    end
  end

  def install
    bin.install Dir["coord-*"].first => "coord"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/coord version")
  end
end
